name: Deploy Crypto News Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch crypto news
        run: python crypto_news.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Prepare files
        run: |
          rm -rf public
          mkdir public
          cp -r dist/* public/
          cp CNAME public/ || true
          ls -la public/

      - name: Check directory before deploy
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== Content of current directory ==="
          ls -la
          echo "=== Content of public directory ==="
          ls -la public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true

      - name: Check directory after deploy
        run: |
          echo "=== Directory after deploy ==="
          ls -la
          ls -la public/ || echo "public directory not found"

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Crypto News Deploy Failed',
              body: 'Failed at: ${{ github.event.head_commit.timestamp }}\nWorkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })
