# .github/workflows/deploy.yml
name: Deploy Crypto News Site

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *" # 4時間ごとに実行
  workflow_dispatch: # 手動実行も可能

# 権限設定を追加
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch crypto news
        run: python crypto_news.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: List dist directory
        run: |
          pwd  # 現在のディレクトリを確認
          ls -la
          ls -la dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Crypto News Deploy Failed',
              body: 'Failed at: ${{ github.event.head_commit.timestamp }}\nWorkflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
            })
